version: "3.9"

services:
  web:
    image: ${DOCKER_IMAGE:-local/vue-spa}:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: cicd-test-web
    restart: unless-stopped
